# Generated by Django 2.2.2 on 2019-06-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qoute',
            options={'ordering': ['-id']},
        ),
    ]
